-- One table: a user's private relationship with one title.
--
-- Shelves are private (settled 2026-08-09). Privacy is enforced here, by Row Level
-- Security, and NOT by application code — the browser talks to PostgREST directly as the
-- signed-in user, so a policy gap is a data leak no amount of careful React can cover.
-- There is deliberately no service-role key anywhere in this project.

create table public.entries (
  -- Defaulted as well as policed. The WITH CHECK policies below are what actually stop a
  -- user writing someone else's row; the default means the client never has to send a
  -- user id at all, so there is no field to get wrong.
  user_id    uuid        not null default auth.uid() references auth.users (id) on delete cascade,

  -- The join key into the catalogue, which lives in git as committed JSON and not in
  -- Postgres. No foreign key is possible and none is wanted: the catalogue is build-time
  -- data regenerated by a pipeline, and mirroring 152 rows into the database would mean a
  -- migration every time the pipeline runs. A slug that matches nothing simply renders
  -- nothing, and only ever on the shelf of the user who wrote it.
  slug       text        not null,

  -- A row exists once a user has engaged with a title at all, so the states are:
  --   watched = false            -> on their watchlist
  --   watched = true             -> watched
  --   rating is not null         -> rated
  -- No status enum, because the two booleans already say it and an enum would need a
  -- migration to add a state.
  watched    boolean     not null default false,

  -- Five stars at half-star precision, stored as 1-10 so it is an integer scale rather
  -- than a float that has to be compared with a tolerance.
  rating     smallint,

  updated_at timestamptz not null default now(),

  primary key (user_id, slug),

  constraint entries_rating_range check (rating between 1 and 10),

  -- Slugs are generated by the pipeline and are always lowercase kebab-case. The bound
  -- stops a signed-in user using their own shelf as free unbounded text storage.
  constraint entries_slug_shape check (slug ~ '^[a-z0-9][a-z0-9-]{0,119}$')
);

comment on table public.entries is
  'A user''s private shelf. One row per title they have watched, rated or listed.';

-- The primary key is (user_id, slug), so its btree already serves "everything belonging
-- to this user" — the only query shape the app has. No further index.

alter table public.entries enable row level security;

-- Four policies rather than one FOR ALL, so that each operation states its own rule and a
-- future change to one cannot silently widen the others.
--
-- `(select auth.uid())` rather than a bare `auth.uid()` is deliberate: wrapping it makes
-- Postgres evaluate it once as an InitPlan instead of once per row.
--
-- `to authenticated` means these are never even evaluated for signed-out visitors. With
-- no policy granting anon anything, anon reads return zero rows.

create policy "Users can read their own entries"
  on public.entries for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their own entries"
  on public.entries for insert to authenticated
  with check ((select auth.uid()) = user_id);

-- USING decides which rows may be updated; WITH CHECK decides what they may be updated
-- to. Both are required — with USING alone, a user could move one of their own rows onto
-- another user's id.
create policy "Users can update their own entries"
  on public.entries for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own entries"
  on public.entries for delete to authenticated
  using ((select auth.uid()) = user_id);

-- Supabase grants both anon and authenticated access to new tables in `public` by
-- default. RLS already denies anon every row; revoking as well means a policy added later
-- without a `to` clause cannot accidentally expose the table to signed-out visitors.
revoke all on public.entries from anon;

-- updated_at is maintained by the database. A client-supplied timestamp is a value
-- somebody has to remember to send on every write, and forgetting is silent.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger entries_touch_updated_at
  before update on public.entries
  for each row execute function public.touch_updated_at();
